### ISSUE TITLE
Copy/paste functionality of the mind map nodes

### ISSUE THREAD

**Issue by cedoor** [Mindmapp/mmp#2]

**Comment by cluxter** [comment]
This feature is critical to me because otherwise we have to delete an re-create nodes every time we want to reassign them, which can be really really time consuming when we have to do it for like 15 branches, each one having 10 branches... There is no way someone will ever delete and re-create 150 nodes one after one. It's a real blocker for productivity. We should make it top priority.

**Comment by cedoor** [comment]
You're right, today I start working on this task! I hope there are no complications.
